package tags

import (
	"steamquack/backend/database"
	"steamquack/backend/models"
	"strings"

	"gorm.io/gorm"
)

func GetBaseTagWeights(gameID uint32) map[string]float64 {

	tagWeights := GetInitialTagWeights()

	// get tag weights using gameID in the db
	// add only if weight > 0.0
	db := database.GetDB()
	var gameTags []models.GameTag
	result := db.Where("game_id = ?", gameID).Find(&gameTags)
	if result.Error != nil {
		return tagWeights
	}

	for _, tag := range gameTags {
		if tag.Weight > 0.0 {
			tagWeights[tag.TagName] = tag.Weight
		}
	}

	return tagWeights

}

func CreateBaseTagWeights(db *gorm.DB, gameID uint32) map[string]float64 {

	tagWeights := GetInitialTagWeights()

	tagCategories := GetAllTagCategories()

	tagsWithCategories := GetAllPossibleTags()

	categoryTotals := make(map[string]uint32)

	for category := range tagCategories {
		categoryTotals[tagCategories[category]] = 0
	}

	//get game tags from steamspy api, assume map[string]uint32 of tag counts is returned called gameTagCounts
	var gameTags []models.GameTag
	result := db.Where("game_id = ?", gameID).Find(&gameTags)
	if result.Error != nil {
		return tagWeights
	}

	gameTagCounts := make(map[string]uint32)
	for _, tag := range gameTags {
		gameTagCounts[strings.ToLower(tag.TagName)] = uint32(tag.Weight)
	}

	for tag, count := range gameTagCounts {
		category := tagsWithCategories[tag]
		categoryTotals[category] += count
	}

	for tag := range tagWeights {
		category := tagsWithCategories[tag]
		if categoryTotals[category] > 0 {
			tagWeights[tag] = float64(gameTagCounts[tag]) / float64(categoryTotals[category])
		}
	}

	for _, gameTag := range gameTags {
		lowerTagName := strings.ToLower(gameTag.TagName)
		if normalizedWeight, exists := tagWeights[lowerTagName]; exists {
			db.Model(&gameTag).Update("weight", normalizedWeight)
		}
	}

	// add tags with no votes with 0.0 weight
	var missingTags []models.GameTag
	for zeroTag := range tagsWithCategories {
		if _, hadVotes := gameTagCounts[zeroTag]; !hadVotes {
			missingTags = append(missingTags, models.GameTag{
				GameID:  uint(gameID),
				TagName: zeroTag,
				Weight:  0.0,
			})
			tagWeights[zeroTag] = 0.0
		}
	}

	if len(missingTags) > 0 {
		db.Create(&missingTags)
	}

	return tagWeights
}

func GetAllTagCategories() []string {

	return []string{
		"super-genre",
		"genre",
		"sub-genre",
		"visuals & viewpoint",
		"themes & moods",
		"features",
		"players",
		"other",
		"software",
		"assessments",
		"ratings",
		"hardware-input",
		"funding",
	}
}

func GetAllPossibleTags() map[string]string {

	return map[string]string{
		"action":     "super-genre",
		"adventure":  "super-genre",
		"casual":     "super-genre",
		"puzzle":     "super-genre",
		"racing":     "super-genre",
		"rpg":        "super-genre",
		"simulation": "super-genre",
		"sports":     "super-genre",
		"strategy":   "super-genre",
		"tabletop":   "super-genre",

		"action rpg":            "genre",
		"action-adventure":      "genre",
		"arcade":                "genre",
		"auto battler":          "genre",
		"automobile sim":        "genre",
		"base building":         "genre",
		"baseball":              "genre",
		"basketball":            "genre",
		"battle royale":         "genre",
		"bmx":                   "genre",
		"board game":            "genre",
		"bowling":               "genre",
		"building":              "genre",
		"card game":             "genre",
		"character action game": "genre",
		"chess":                 "genre",
		"clicker":               "genre",
		"cycling":               "genre",
		"diplomacy":             "genre",
		"e-sports":              "genre",
		"esports":               "genre",
		"experimental":          "genre",
		"exploration":           "genre",
		"farming sim":           "genre",
		"fighting":              "genre",
		"football":              "genre",
		"god game":              "genre",
		"golf":                  "genre",
		"hacking":               "genre",
		"hidden object":         "genre",
		"hockey":                "genre",
		"idler":                 "genre",
		"interactive fiction":   "genre",
		"management":            "genre",
		"match 3":               "genre",
		"medical sim":           "genre",
		"mini golf":             "genre",
		"mining":                "genre",
		"mmorpg":                "genre",
		"moba":                  "genre",
		"motocross":             "genre",
		"open world":            "genre",
		"outbreak sim":          "genre",
		"party-based rpg":       "genre",
		"pinball":               "genre",
		"platformer":            "genre",
		"point & click":         "genre",
		"rhythm":                "genre",
		"roguelike":             "genre",
		"rts":                   "genre",
		"sandbox":               "genre",
		"shooter":               "genre",
		"skateboarding":         "genre",
		"skating":               "genre",
		"skiing":                "genre",
		"snowboarding":          "genre",
		"soccer":                "genre",
		"space sim":             "genre",
		"stealth":               "genre",
		"strategy rpg":          "genre",
		"survival":              "genre",
		"tennis":                "genre",
		"tower defense":         "genre",
		"trivia":                "genre",
		"turn-based strategy":   "genre",
		"visual novel":          "genre",
		"walking simulator":     "genre",
		"word game":             "genre",
		"wrestling":             "genre",

		"2d fighter":                "sub-genre",
		"2d platformer":             "sub-genre",
		"3d fighter":                "sub-genre",
		"3d platformer":             "sub-genre",
		"4x":                        "sub-genre",
		"action roguelike":          "sub-genre",
		"arena shooter":             "sub-genre",
		"beat 'em up":               "sub-genre",
		"bullet hell":               "sub-genre",
		"card battler":              "sub-genre",
		"choose your own adventure": "sub-genre",
		"city builder":              "sub-genre",
		"collectathon":              "sub-genre",
		"colony sim":                "sub-genre",
		"combat racing":             "sub-genre",
		"crpg":                      "sub-genre",
		"dating sim":                "sub-genre",
		"dungeon crawler":           "sub-genre",
		"education":                 "sub-genre",
		"flight":                    "sub-genre",
		"fps":                       "sub-genre",
		"grand strategy":            "sub-genre",
		"hack and slash":            "sub-genre",
		"heist":                     "sub-genre",
		"hero shooter":              "sub-genre",
		"horror":                    "sub-genre",
		"immersive sim":             "sub-genre",
		"investigation":             "sub-genre",
		"jrpg":                      "sub-genre",
		"life sim":                  "sub-genre",
		"looter shooter":            "sub-genre",
		"metroidvania":              "sub-genre",
		"mystery dungeon":           "sub-genre",
		"on-rails shooter":          "sub-genre",
		"open world survival craft": "sub-genre",
		"political sim":             "sub-genre",
		"precision platformer":      "sub-genre",
		"programming":               "sub-genre",
		"real time tactics":         "sub-genre",
		"roguelite":                 "sub-genre",
		"roguevania":                "sub-genre",
		"runner":                    "sub-genre",
		"shoot 'em up":              "sub-genre",
		"side scroller":             "sub-genre",
		"sokoban":                   "sub-genre",
		"solitaire":                 "sub-genre",
		"souls-like":                "sub-genre",
		"spectacle fighter":         "sub-genre",
		"spelling":                  "sub-genre",
		"psychological horror":      "sub-genre",
		"survival horror":           "sub-genre",
		"tactical rpg":              "sub-genre",
		"third-person shooter":      "sub-genre",
		"time management":           "sub-genre",
		"top-down shooter":          "sub-genre",
		"trading":                   "sub-genre",
		"trading card game":         "sub-genre",
		"traditional roguelike":     "sub-genre",
		"turn-based tactics":        "sub-genre",
		"twin stick shooter":        "sub-genre",
		"typing":                    "sub-genre",
		"wargame":                   "sub-genre",

		"2.5d":           "visuals & viewpoint",
		"2d":             "visuals & viewpoint",
		"360 video":      "visuals & viewpoint",
		"3d":             "visuals & viewpoint",
		"3d vision":      "visuals & viewpoint",
		"abstract":       "visuals & viewpoint",
		"anime":          "visuals & viewpoint",
		"cartoon":        "visuals & viewpoint",
		"cartoony":       "visuals & viewpoint",
		"cinematic":      "visuals & viewpoint",
		"colorful":       "visuals & viewpoint",
		"comic book":     "visuals & viewpoint",
		"cute":           "visuals & viewpoint",
		"first-person":   "visuals & viewpoint",
		"hand-drawn":     "visuals & viewpoint",
		"isometric":      "visuals & viewpoint",
		"minimalist":     "visuals & viewpoint",
		"noir":           "visuals & viewpoint",
		"pixel graphics": "visuals & viewpoint",
		"psychedelic":    "visuals & viewpoint",
		"realistic":      "visuals & viewpoint",
		"split screen":   "visuals & viewpoint",
		"stylized":       "visuals & viewpoint",
		"third person":   "visuals & viewpoint",
		"top-down":       "visuals & viewpoint",
		"voxel":          "visuals & viewpoint",
		"vr":             "visuals & viewpoint",

		"1980s":             "themes & moods",
		"1990's":            "themes & moods",
		"agriculture":       "themes & moods",
		"aliens":            "themes & moods",
		"alternate history": "themes & moods",
		"america":           "themes & moods",
		"atmospheric":       "themes & moods",
		"assassin":          "themes & moods",
		"bikes":             "themes & moods",
		"capitalism":        "themes & moods",
		"cats":              "themes & moods",
		"cold war":          "themes & moods",
		"conspiracy":        "themes & moods",
		"crime":             "themes & moods",
		"cyberpunk":         "themes & moods",
		"dark":              "themes & moods",
		"dark fantasy":      "themes & moods",
		"demons":            "themes & moods",
		"destruction":       "themes & moods",
		"detective":         "themes & moods",
		"dinosaurs":         "themes & moods",
		"dog":               "themes & moods",
		"dragons":           "themes & moods",
		"dynamic narration": "themes & moods",
		"economy":           "themes & moods",
		"faith":             "themes & moods",
		"family friendly":   "themes & moods",
		"fantasy":           "themes & moods",
		"foreign":           "themes & moods",
		"futuristic":        "themes & moods",
		"gambling":          "themes & moods",
		"game development":  "themes & moods",
		"gothic":            "themes & moods",
		"historical":        "themes & moods",
		"horses":            "themes & moods",
		"illuminati":        "themes & moods",
		"jet":               "themes & moods",
		"lemmings":          "themes & moods",
		"lgbtq+":            "themes & moods",
		"logic":             "themes & moods",
		"loot":              "themes & moods",
		"lovecraftian":      "themes & moods",
		"magic":             "themes & moods",
		"mars":              "themes & moods",
		"mechs":             "themes & moods",
		"medieval":          "themes & moods",
		"memes":             "themes & moods",
		"military":          "themes & moods",
		"modern":            "themes & moods",
		"motorbike":         "themes & moods",
		"mystery":           "themes & moods",
		"mythology":         "themes & moods",
		"nature":            "themes & moods",
		"naval":             "themes & moods",
		"ninja":             "themes & moods",
		"offroad":           "themes & moods",
		"old school":        "themes & moods",
		"otome":             "themes & moods",
		"parkour":           "themes & moods",
		"philosophical":     "themes & moods",
		"pirates":           "themes & moods",
		"political":         "themes & moods",
		"politics":          "themes & moods",
		"pool":              "themes & moods",
		"post-apocalyptic":  "themes & moods",
		"nostalgia":         "themes & moods",
		"retro":             "themes & moods",
		"robots":            "themes & moods",
		"romance":           "themes & moods",
		"rome":              "themes & moods",
		"satire":            "themes & moods",
		"science":           "themes & moods",
		"sci-fi":            "themes & moods",
		"sniper":            "themes & moods",
		"snow":              "themes & moods",
		"space":             "themes & moods",
		"steampunk":         "themes & moods",
		"submarine":         "themes & moods",
		"superhero":         "themes & moods",
		"supernatural":      "themes & moods",
		"surreal":           "themes & moods",
		"swordplay":         "themes & moods",
		"tactical":          "themes & moods",
		"tanks":             "themes & moods",
		"thriller":          "themes & moods",
		"time travel":       "themes & moods",
		"trains":            "themes & moods",
		"transhumanism":     "themes & moods",
		"transportation":    "themes & moods",
		"underground":       "themes & moods",
		"underwater":        "themes & moods",
		"vampire":           "themes & moods",
		"war":               "themes & moods",
		"werewolves":        "themes & moods",
		"western":           "themes & moods",
		"world war i":       "themes & moods",
		"world war ii":      "themes & moods",

		"6dof":                              "features",
		"archery":                           "features",
		"artificial intelligence":           "features",
		"asymmetric vr":                     "features",
		"atv":                               "features",
		"automation":                        "features",
		"boxing":                            "features",
		"bullet time":                       "features",
		"character customization":           "features",
		"choices matter":                    "features",
		"class-based":                       "features",
		"combat":                            "features",
		"conversation":                      "features",
		"crafting":                          "features",
		"deckbuilding":                      "features",
		"driving":                           "features",
		"fmv":                               "features",
		"grid-based movement":               "features",
		"gun customization":                 "features",
		"hex grid":                          "features",
		"hunting":                           "features",
		"inventory management":              "features",
		"level editor":                      "features",
		"linear":                            "features",
		"martial arts":                      "features",
		"moddable":                          "features",
		"multiple endings":                  "features",
		"music-based procedural generation": "features",
		"narration":                         "features",
		"naval combat":                      "features",
		"nonlinear":                         "features",
		"perma death":                       "features",
		"physics":                           "features",
		"procedural generation":             "features",
		"pve":                               "features",
		"pvp":                               "features",
		"quick-time events":                 "features",
		"resource management":               "features",
		"sailing":                           "features",
		"score attack":                      "features",
		"story rich":                        "features",
		"team-based":                        "features",
		"text-based":                        "features",
		"time manipulation":                 "features",
		"turn-based combat":                 "features",
		"tutorial":                          "features",
		"vehicular combat":                  "features",
		"female protagonist":                "features",
		"silent protagonist":                "features",
		"villain protagonist":               "features",
		"minigames":                         "features",
		"intentionally awkward controls":    "features",

		"4 player local":           "players",
		"asynchronous multiplayer": "players",
		"co-op":                    "players",
		"co-op campaign":           "players",
		"local co-op":              "players",
		"local multiplayer":        "players",
		"massively multiplayer":    "players",
		"multiplayer":              "players",
		"online co-op":             "players",
		"singleplayer":             "players",

		"based on a novel":     "other",
		"batman":               "other",
		"documentary":          "other",
		"drama":                "other",
		"dungeons & dragons":   "other",
		"episodic":             "other",
		"experience":           "other",
		"feature film":         "other",
		"games workshop":       "other",
		"indie":                "other",
		"lara croft":           "other",
		"lego":                 "other",
		"mod":                  "other",
		"movie":                "other",
		"music":                "other",
		"real-time":            "other",
		"real-time with pause": "other",
		"remake":               "other",
		"sequel":               "other",
		"soundtrack":           "other",
		"star wars":            "other",
		"time attack":          "other",
		"turn-based":           "other",
		"warhammer 40k":        "other",

		"animation & modeling":  "software",
		"audio production":      "software",
		"benchmark":             "software",
		"design & illustration": "software",
		"gamemaker":             "software",
		"gaming":                "software",
		"photo editing":         "software",
		"rpgmaker":              "software",
		"software":              "software",
		"software training":     "software",
		"utilities":             "software",
		"video production":      "software",
		"web publishing":        "software",

		"addictive":        "assessments",
		"beautiful":        "assessments",
		"classic":          "assessments",
		"competitive":      "assessments",
		"cult classic":     "assessments",
		"difficult":        "assessments",
		"emotional":        "assessments",
		"epic":             "assessments",
		"fast-paced":       "assessments",
		"funny":            "assessments",
		"great soundtrack": "assessments",
		"lore-rich":        "assessments",
		"masterpiece":      "assessments",
		"psychological":    "assessments",
		"relaxing":         "assessments",
		"replay value":     "assessments",
		"short":            "assessments",
		"unforgiving":      "assessments",
		"comedy":           "assessments",
		"dark comedy":      "assessments",

		"blood":          "ratings",
		"gore":           "ratings",
		"mature":         "ratings",
		"nsfw":           "ratings",
		"nudity":         "ratings",
		"sexual content": "ratings",
		"violent":        "ratings",

		"controller":     "hardware-input",
		"hardware":       "hardware-input",
		"mouse only":     "hardware-input",
		"steam machine":  "hardware-input",
		"touch-friendly": "hardware-input",
		"trackir":        "hardware-input",
		"voice control":  "hardware-input",

		"crowdfunded":  "funding",
		"early access": "funding",
		"free to play": "funding",
		"kickstarter":  "funding",
	}
}

func GetInitialTagWeights() map[string]float64 {
	return map[string]float64{
		"action":     0.0,
		"adventure":  0.0,
		"casual":     0.0,
		"puzzle":     0.0,
		"racing":     0.0,
		"rpg":        0.0,
		"simulation": 0.0,
		"sports":     0.0,
		"strategy":   0.0,
		"tabletop":   0.0,

		"action rpg":            0.0,
		"action-adventure":      0.0,
		"arcade":                0.0,
		"auto battler":          0.0,
		"automobile sim":        0.0,
		"base building":         0.0,
		"baseball":              0.0,
		"basketball":            0.0,
		"battle royale":         0.0,
		"bmx":                   0.0,
		"board game":            0.0,
		"bowling":               0.0,
		"building":              0.0,
		"card game":             0.0,
		"character action game": 0.0,
		"chess":                 0.0,
		"clicker":               0.0,
		"cycling":               0.0,
		"diplomacy":             0.0,
		"e-sports":              0.0,
		"esports":               0.0,
		"experimental":          0.0,
		"exploration":           0.0,
		"farming sim":           0.0,
		"fighting":              0.0,
		"football":              0.0,
		"god game":              0.0,
		"golf":                  0.0,
		"hacking":               0.0,
		"hidden object":         0.0,
		"hockey":                0.0,
		"idler":                 0.0,
		"interactive fiction":   0.0,
		"management":            0.0,
		"match 3":               0.0,
		"medical sim":           0.0,
		"mini golf":             0.0,
		"mining":                0.0,
		"mmorpg":                0.0,
		"moba":                  0.0,
		"motocross":             0.0,
		"open world":            0.0,
		"outbreak sim":          0.0,
		"party-based rpg":       0.0,
		"pinball":               0.0,
		"platformer":            0.0,
		"point & click":         0.0,
		"rhythm":                0.0,
		"roguelike":             0.0,
		"rts":                   0.0,
		"sandbox":               0.0,
		"shooter":               0.0,
		"skateboarding":         0.0,
		"skating":               0.0,
		"skiing":                0.0,
		"snowboarding":          0.0,
		"soccer":                0.0,
		"space sim":             0.0,
		"stealth":               0.0,
		"strategy rpg":          0.0,
		"survival":              0.0,
		"tennis":                0.0,
		"tower defense":         0.0,
		"trivia":                0.0,
		"turn-based strategy":   0.0,
		"visual novel":          0.0,
		"walking simulator":     0.0,
		"word game":             0.0,
		"wrestling":             0.0,

		"2d fighter":                0.0,
		"2d platformer":             0.0,
		"3d fighter":                0.0,
		"3d platformer":             0.0,
		"4x":                        0.0,
		"action roguelike":          0.0,
		"arena shooter":             0.0,
		"beat 'em up":               0.0,
		"bullet hell":               0.0,
		"card battler":              0.0,
		"choose your own adventure": 0.0,
		"city builder":              0.0,
		"collectathon":              0.0,
		"colony sim":                0.0,
		"combat racing":             0.0,
		"crpg":                      0.0,
		"dating sim":                0.0,
		"dungeon crawler":           0.0,
		"education":                 0.0,
		"flight":                    0.0,
		"fps":                       0.0,
		"grand strategy":            0.0,
		"hack and slash":            0.0,
		"heist":                     0.0,
		"hero shooter":              0.0,
		"horror":                    0.0,
		"immersive sim":             0.0,
		"investigation":             0.0,
		"jrpg":                      0.0,
		"life sim":                  0.0,
		"looter shooter":            0.0,
		"metroidvania":              0.0,
		"mystery dungeon":           0.0,
		"on-rails shooter":          0.0,
		"open world survival craft": 0.0,
		"political sim":             0.0,
		"precision platformer":      0.0,
		"programming":               0.0,
		"real time tactics":         0.0,
		"roguelite":                 0.0,
		"roguevania":                0.0,
		"runner":                    0.0,
		"shoot 'em up":              0.0,
		"side scroller":             0.0,
		"sokoban":                   0.0,
		"solitaire":                 0.0,
		"souls-like":                0.0,
		"spectacle fighter":         0.0,
		"spelling":                  0.0,
		"psychological horror":      0.0,
		"survival horror":           0.0,
		"tactical rpg":              0.0,
		"third-person shooter":      0.0,
		"time management":           0.0,
		"top-down shooter":          0.0,
		"trading":                   0.0,
		"trading card game":         0.0,
		"traditional roguelike":     0.0,
		"turn-based tactics":        0.0,
		"twin stick shooter":        0.0,
		"typing":                    0.0,
		"wargame":                   0.0,

		"2.5d":           0.0,
		"2d":             0.0,
		"360 video":      0.0,
		"3d":             0.0,
		"3d vision":      0.0,
		"abstract":       0.0,
		"anime":          0.0,
		"cartoon":        0.0,
		"cartoony":       0.0,
		"cinematic":      0.0,
		"colorful":       0.0,
		"comic book":     0.0,
		"cute":           0.0,
		"first-person":   0.0,
		"hand-drawn":     0.0,
		"isometric":      0.0,
		"minimalist":     0.0,
		"noir":           0.0,
		"pixel graphics": 0.0,
		"psychedelic":    0.0,
		"realistic":      0.0,
		"split screen":   0.0,
		"stylized":       0.0,
		"third person":   0.0,
		"top-down":       0.0,
		"voxel":          0.0,
		"vr":             0.0,

		"1980s":             0.0,
		"1990's":            0.0,
		"agriculture":       0.0,
		"aliens":            0.0,
		"alternate history": 0.0,
		"america":           0.0,
		"atmospheric":       0.0,
		"assassin":          0.0,
		"bikes":             0.0,
		"capitalism":        0.0,
		"cats":              0.0,
		"cold war":          0.0,
		"conspiracy":        0.0,
		"crime":             0.0,
		"cyberpunk":         0.0,
		"dark":              0.0,
		"dark fantasy":      0.0,
		"demons":            0.0,
		"destruction":       0.0,
		"detective":         0.0,
		"dinosaurs":         0.0,
		"dog":               0.0,
		"dragons":           0.0,
		"dynamic narration": 0.0,
		"economy":           0.0,
		"faith":             0.0,
		"family friendly":   0.0,
		"fantasy":           0.0,
		"foreign":           0.0,
		"futuristic":        0.0,
		"gambling":          0.0,
		"game development":  0.0,
		"gothic":            0.0,
		"historical":        0.0,
		"horses":            0.0,
		"illuminati":        0.0,
		"jet":               0.0,
		"lemmings":          0.0,
		"lgbtq+":            0.0,
		"logic":             0.0,
		"loot":              0.0,
		"lovecraftian":      0.0,
		"magic":             0.0,
		"mars":              0.0,
		"mechs":             0.0,
		"medieval":          0.0,
		"memes":             0.0,
		"military":          0.0,
		"modern":            0.0,
		"motorbike":         0.0,
		"mystery":           0.0,
		"mythology":         0.0,
		"nature":            0.0,
		"naval":             0.0,
		"ninja":             0.0,
		"offroad":           0.0,
		"old school":        0.0,
		"otome":             0.0,
		"parkour":           0.0,
		"philosophical":     0.0,
		"pirates":           0.0,
		"political":         0.0,
		"politics":          0.0,
		"pool":              0.0,
		"post-apocalyptic":  0.0,
		"nostalgia":         0.0,
		"retro":             0.0,
		"robots":            0.0,
		"romance":           0.0,
		"rome":              0.0,
		"satire":            0.0,
		"science":           0.0,
		"sci-fi":            0.0,
		"sniper":            0.0,
		"snow":              0.0,
		"space":             0.0,
		"steampunk":         0.0,
		"submarine":         0.0,
		"superhero":         0.0,
		"supernatural":      0.0,
		"surreal":           0.0,
		"swordplay":         0.0,
		"tactical":          0.0,
		"tanks":             0.0,
		"thriller":          0.0,
		"time travel":       0.0,
		"trains":            0.0,
		"transhumanism":     0.0,
		"transportation":    0.0,
		"underground":       0.0,
		"underwater":        0.0,
		"vampire":           0.0,
		"war":               0.0,
		"werewolves":        0.0,
		"western":           0.0,
		"world war i":       0.0,
		"world war ii":      0.0,

		"6dof":                              0.0,
		"archery":                           0.0,
		"artificial intelligence":           0.0,
		"asymmetric vr":                     0.0,
		"atv":                               0.0,
		"automation":                        0.0,
		"boxing":                            0.0,
		"bullet time":                       0.0,
		"character customization":           0.0,
		"choices matter":                    0.0,
		"class-based":                       0.0,
		"combat":                            0.0,
		"conversation":                      0.0,
		"crafting":                          0.0,
		"deckbuilding":                      0.0,
		"driving":                           0.0,
		"fmv":                               0.0,
		"grid-based movement":               0.0,
		"gun customization":                 0.0,
		"hex grid":                          0.0,
		"hunting":                           0.0,
		"inventory management":              0.0,
		"level editor":                      0.0,
		"linear":                            0.0,
		"martial arts":                      0.0,
		"moddable":                          0.0,
		"multiple endings":                  0.0,
		"music-based procedural generation": 0.0,
		"narration":                         0.0,
		"naval combat":                      0.0,
		"nonlinear":                         0.0,
		"perma death":                       0.0,
		"physics":                           0.0,
		"procedural generation":             0.0,
		"pve":                               0.0,
		"pvp":                               0.0,
		"quick-time events":                 0.0,
		"resource management":               0.0,
		"sailing":                           0.0,
		"score attack":                      0.0,
		"story rich":                        0.0,
		"team-based":                        0.0,
		"text-based":                        0.0,
		"time manipulation":                 0.0,
		"turn-based combat":                 0.0,
		"tutorial":                          0.0,
		"vehicular combat":                  0.0,
		"female protagonist":                0.0,
		"silent protagonist":                0.0,
		"villain protagonist":               0.0,
		"minigames":                         0.0,
		"intentionally awkward controls":    0.0,

		"4 player local":           0.0,
		"asynchronous multiplayer": 0.0,
		"co-op":                    0.0,
		"co-op campaign":           0.0,
		"local co-op":              0.0,
		"local multiplayer":        0.0,
		"massively multiplayer":    0.0,
		"multiplayer":              0.0,
		"online co-op":             0.0,
		"singleplayer":             0.0,

		"based on a novel":     0.0,
		"batman":               0.0,
		"documentary":          0.0,
		"drama":                0.0,
		"dungeons & dragons":   0.0,
		"episodic":             0.0,
		"experience":           0.0,
		"feature film":         0.0,
		"games workshop":       0.0,
		"indie":                0.0,
		"lara croft":           0.0,
		"lego":                 0.0,
		"mod":                  0.0,
		"movie":                0.0,
		"music":                0.0,
		"real-time":            0.0,
		"real-time with pause": 0.0,
		"remake":               0.0,
		"sequel":               0.0,
		"soundtrack":           0.0,
		"star wars":            0.0,
		"time attack":          0.0,
		"turn-based":           0.0,
		"warhammer 40k":        0.0,

		"animation & modeling":  0.0,
		"audio production":      0.0,
		"benchmark":             0.0,
		"design & illustration": 0.0,
		"gamemaker":             0.0,
		"gaming":                0.0,
		"photo editing":         0.0,
		"rpgmaker":              0.0,
		"software":              0.0,
		"software training":     0.0,
		"utilities":             0.0,
		"video production":      0.0,
		"web publishing":        0.0,

		"addictive":        0.0,
		"beautiful":        0.0,
		"classic":          0.0,
		"competitive":      0.0,
		"cult classic":     0.0,
		"difficult":        0.0,
		"emotional":        0.0,
		"epic":             0.0,
		"fast-paced":       0.0,
		"funny":            0.0,
		"great soundtrack": 0.0,
		"lore-rich":        0.0,
		"masterpiece":      0.0,
		"psychological":    0.0,
		"relaxing":         0.0,
		"replay value":     0.0,
		"short":            0.0,
		"unforgiving":      0.0,
		"comedy":           0.0,
		"dark comedy":      0.0,

		"blood":          0.0,
		"gore":           0.0,
		"mature":         0.0,
		"nsfw":           0.0,
		"nudity":         0.0,
		"sexual content": 0.0,
		"violent":        0.0,

		"controller":     0.0,
		"hardware":       0.0,
		"mouse only":     0.0,
		"steam machine":  0.0,
		"touch-friendly": 0.0,
		"trackir":        0.0,
		"voice control":  0.0,

		"crowdfunded":  0.0,
		"early access": 0.0,
		"free to play": 0.0,
		"kickstarter":  0.0,
	}
}
