package tags

import (
	"fmt"
	"steamquack/backend/database"
	"steamquack/backend/models"
)

var allTagCategories = []string{
	"super-genre",
	"genre",
	"sub-genre",
	"visuals & viewpoint",
	"themes & moods",
	"features",
	"players",
	"other",
	"software",
	"assessments",
	"ratings",
	"hardware-input",
	"funding",
}

var tagCategoryWeights = map[string]float64{
	"super-genre":         0.125,
	"genre":               0.75,
	"sub-genre":           1.0,
	"visuals & viewpoint": 0.5,
	"themes & moods":      0.5,
	"features":            0.25,
	"players":             0.125,
	"other":               0.125,
	"software":            0.125,
	"assessments":         0.5,
	"ratings":             0.05,
	"hardware-input":      0.05,
	"funding":             0.025,
}

var allPossibleTags = map[string]string{
	"Action":     "super-genre",
	"Adventure":  "super-genre",
	"Casual":     "super-genre",
	"Puzzle":     "super-genre",
	"Racing":     "super-genre",
	"RPG":        "super-genre",
	"Simulation": "super-genre",
	"Sports":     "super-genre",
	"Strategy":   "super-genre",
	"Tabletop":   "super-genre",

	"Action RPG":            "genre",
	"Action-Adventure":      "genre",
	"Arcade":                "genre",
	"Auto Battler":          "genre",
	"Automobile Sim":        "genre",
	"Base-Building":         "genre",
	"Baseball":              "genre",
	"Basketball":            "genre",
	"Battle Royale":         "genre",
	"BMX":                   "genre",
	"Board Game":            "genre",
	"Bowling":               "genre",
	"Building":              "genre",
	"Card Game":             "genre",
	"Character Action Game": "genre",
	"Chess":                 "genre",
	"Clicker":               "genre",
	"Cycling":               "genre",
	"Diplomacy":             "genre",
	"e-sports":              "genre",
	"Experimental":          "genre",
	"Exploration":           "genre",
	"Farming Sim":           "genre",
	"Fighting":              "genre",
	"Football":              "genre",
	"God Game":              "genre",
	"Golf":                  "genre",
	"Hacking":               "genre",
	"Hidden Object":         "genre",
	"Hockey":                "genre",
	"Idler":                 "genre",
	"Interactive Fiction":   "genre",
	"Management":            "genre",
	"Match 3":               "genre",
	"Medical Sim":           "genre",
	"Mini Golf":             "genre",
	"Mining":                "genre",
	"MMORPG":                "genre",
	"MOBA":                  "genre",
	"Motocross":             "genre",
	"Open World":            "genre",
	"Outbreak Sim":          "genre",
	"Party-Based RPG":       "genre",
	"Pinball":               "genre",
	"Platformer":            "genre",
	"Point & Click":         "genre",
	"Rhythm":                "genre",
	"Rogue-like":            "genre",
	"RTS":                   "genre",
	"Sandbox":               "genre",
	"Shooter":               "genre",
	"Skateboarding":         "genre",
	"Skating":               "genre",
	"Skiing":                "genre",
	"Snowboarding":          "genre",
	"Football (Soccer)":     "genre",
	"Space Sim":             "genre",
	"Stealth":               "genre",
	"Strategy RPG":          "genre",
	"Survival":              "genre",
	"Tennis":                "genre",
	"Tower Defense":         "genre",
	"Trivia":                "genre",
	"Turn-Based Strategy":   "genre",
	"Visual Novel":          "genre",
	"Walking Simulator":     "genre",
	"Word Game":             "genre",
	"Wrestling":             "genre",

	"2D Fighter":                "sub-genre",
	"2D Platformer":             "sub-genre",
	"3D Fighter":                "sub-genre",
	"3D Platformer":             "sub-genre",
	"4X":                        "sub-genre",
	"Action Roguelike":          "sub-genre",
	"Arena Shooter":             "sub-genre",
	"Beat 'em up":               "sub-genre",
	"Bullet Hell":               "sub-genre",
	"Card Battler":              "sub-genre",
	"Choose Your Own Adventure": "sub-genre",
	"City Builder":              "sub-genre",
	"Collectathon":              "sub-genre",
	"Colony Sim":                "sub-genre",
	"Combat Racing":             "sub-genre",
	"CRPG":                      "sub-genre",
	"Dating Sim":                "sub-genre",
	"Dungeon Crawler":           "sub-genre",
	"Education":                 "sub-genre",
	"Flight":                    "sub-genre",
	"FPS":                       "sub-genre",
	"Grand Strategy":            "sub-genre",
	"Hack and Slash":            "sub-genre",
	"Heist":                     "sub-genre",
	"Hero Shooter":              "sub-genre",
	"Horror":                    "sub-genre",
	"Immersive Sim":             "sub-genre",
	"Investigation":             "sub-genre",
	"JRPG":                      "sub-genre",
	"Life Sim":                  "sub-genre",
	"Looter Shooter":            "sub-genre",
	"Metroidvania":              "sub-genre",
	"Mystery Dungeon":           "sub-genre",
	"On-Rails Shooter":          "sub-genre",
	"Open World Survival Craft": "sub-genre",
	"Political Sim":             "sub-genre",
	"Precision Platformer":      "sub-genre",
	"Programming":               "sub-genre",
	"Real Time Tactics":         "sub-genre",
	"Rogue-lite":                "sub-genre",
	"Roguevania":                "sub-genre",
	"Runner":                    "sub-genre",
	"Shoot 'Em Up":              "sub-genre",
	"Side Scroller":             "sub-genre",
	"Sokoban":                   "sub-genre",
	"Solitaire":                 "sub-genre",
	"Souls-like":                "sub-genre",
	"Spectacle fighter":         "sub-genre",
	"Spelling":                  "sub-genre",
	"Psychological Horror":      "sub-genre",
	"Survival Horror":           "sub-genre",
	"Tactical RPG":              "sub-genre",
	"Third-Person Shooter":      "sub-genre",
	"Time Management":           "sub-genre",
	"Top-Down Shooter":          "sub-genre",
	"Trading":                   "sub-genre",
	"Trading Card Game":         "sub-genre",
	"Traditional Roguelike":     "sub-genre",
	"Turn-Based Tactics":        "sub-genre",
	"Twin Stick Shooter":        "sub-genre",
	"Typing":                    "sub-genre",
	"Wargame":                   "sub-genre",

	"2.5D":           "visuals & viewpoint",
	"2D":             "visuals & viewpoint",
	"360 Video":      "visuals & viewpoint",
	"3D":             "visuals & viewpoint",
	"3D Vision":      "visuals & viewpoint",
	"Abstract":       "visuals & viewpoint",
	"Anime":          "visuals & viewpoint",
	"Cartoon":        "visuals & viewpoint",
	"Cartoony":       "visuals & viewpoint",
	"Cinematic":      "visuals & viewpoint",
	"Colorful":       "visuals & viewpoint",
	"Comic Book":     "visuals & viewpoint",
	"Cute":           "visuals & viewpoint",
	"First-Person":   "visuals & viewpoint",
	"Hand-drawn":     "visuals & viewpoint",
	"Isometric":      "visuals & viewpoint",
	"Minimalist":     "visuals & viewpoint",
	"Noir":           "visuals & viewpoint",
	"Pixel Graphics": "visuals & viewpoint",
	"Psychedelic":    "visuals & viewpoint",
	"Realistic":      "visuals & viewpoint",
	"Split Screen":   "visuals & viewpoint",
	"Stylized":       "visuals & viewpoint",
	"Third Person":   "visuals & viewpoint",
	"Top-Down":       "visuals & viewpoint",
	"Voxel":          "visuals & viewpoint",
	"VR":             "visuals & viewpoint",

	"1980s":             "themes & moods",
	"1990's":            "themes & moods",
	"Agriculture":       "themes & moods",
	"Aliens":            "themes & moods",
	"Alternate History": "themes & moods",
	"America":           "themes & moods",
	"Atmospheric":       "themes & moods",
	"Assassin":          "themes & moods",
	"Bikes":             "themes & moods",
	"Capitalism":        "themes & moods",
	"Cats":              "themes & moods",
	"Cold War":          "themes & moods",
	"Conspiracy":        "themes & moods",
	"Crime":             "themes & moods",
	"Cyberpunk":         "themes & moods",
	"Dark":              "themes & moods",
	"Dark Fantasy":      "themes & moods",
	"Demons":            "themes & moods",
	"Destruction":       "themes & moods",
	"Detective":         "themes & moods",
	"Dinosaurs":         "themes & moods",
	"Dog":               "themes & moods",
	"Dragons":           "themes & moods",
	"Dynamic Narration": "themes & moods",
	"Economy":           "themes & moods",
	"Faith":             "themes & moods",
	"Family Friendly":   "themes & moods",
	"Fantasy":           "themes & moods",
	"Foreign":           "themes & moods",
	"Futuristic":        "themes & moods",
	"Gambling":          "themes & moods",
	"Game Development":  "themes & moods",
	"Gothic":            "themes & moods",
	"Historical":        "themes & moods",
	"Horses":            "themes & moods",
	"Illuminati":        "themes & moods",
	"Jet":               "themes & moods",
	"Lemmings":          "themes & moods",
	"LGBTQ+":            "themes & moods",
	"Logic":             "themes & moods",
	"Loot":              "themes & moods",
	"Lovecraftian":      "themes & moods",
	"Magic":             "themes & moods",
	"Mars":              "themes & moods",
	"Mechs":             "themes & moods",
	"Medieval":          "themes & moods",
	"Memes":             "themes & moods",
	"Military":          "themes & moods",
	"Modern":            "themes & moods",
	"Motorbike":         "themes & moods",
	"Mystery":           "themes & moods",
	"Mythology":         "themes & moods",
	"Nature":            "themes & moods",
	"Naval":             "themes & moods",
	"Ninja":             "themes & moods",
	"Offroad":           "themes & moods",
	"Old School":        "themes & moods",
	"Otome":             "themes & moods",
	"Parkour":           "themes & moods",
	"Philosophical":     "themes & moods",
	"Pirates":           "themes & moods",
	"Political":         "themes & moods",
	"Politics":          "themes & moods",
	"Pool":              "themes & moods",
	"Post-apocalyptic":  "themes & moods",
	"Nostalgia":         "themes & moods",
	"Retro":             "themes & moods",
	"Robots":            "themes & moods",
	"Romance":           "themes & moods",
	"Rome":              "themes & moods",
	"Satire":            "themes & moods",
	"Science":           "themes & moods",
	"Sci-fi":            "themes & moods",
	"Sniper":            "themes & moods",
	"Snow":              "themes & moods",
	"Space":             "themes & moods",
	"Steampunk":         "themes & moods",
	"Submarine":         "themes & moods",
	"Superhero":         "themes & moods",
	"Supernatural":      "themes & moods",
	"Surreal":           "themes & moods",
	"Swordplay":         "themes & moods",
	"Tactical":          "themes & moods",
	"Tanks":             "themes & moods",
	"Thriller":          "themes & moods",
	"Time Travel":       "themes & moods",
	"Trains":            "themes & moods",
	"Transhumanism":     "themes & moods",
	"Transportation":    "themes & moods",
	"Underground":       "themes & moods",
	"Underwater":        "themes & moods",
	"Vampire":           "themes & moods",
	"War":               "themes & moods",
	"Werewolves":        "themes & moods",
	"Western":           "themes & moods",
	"World War I":       "themes & moods",
	"World War II":      "themes & moods",

	"6DOF":                              "features",
	"Archery":                           "features",
	"Artificial Intelligence":           "features",
	"Asymmetric VR":                     "features",
	"ATV":                               "features",
	"Automation":                        "features",
	"Boxing":                            "features",
	"Bullet Time":                       "features",
	"Character Customization":           "features",
	"Choices Matter":                    "features",
	"Class-Based":                       "features",
	"Combat":                            "features",
	"Conversation":                      "features",
	"Crafting":                          "features",
	"Deckbuilding":                      "features",
	"Driving":                           "features",
	"FMV":                               "features",
	"Grid-Based Movement":               "features",
	"Gun Customization":                 "features",
	"Hex Grid":                          "features",
	"Hunting":                           "features",
	"Inventory Management":              "features",
	"Level Editor":                      "features",
	"Linear":                            "features",
	"Martial Arts":                      "features",
	"Moddable":                          "features",
	"Multiple Endings":                  "features",
	"Music-Based Procedural Generation": "features",
	"Narration":                         "features",
	"Naval Combat":                      "features",
	"Nonlinear":                         "features",
	"Perma Death":                       "features",
	"Physics":                           "features",
	"Procedural Generation":             "features",
	"PvE":                               "features",
	"PvP":                               "features",
	"Quick-Time Events":                 "features",
	"Resource Management":               "features",
	"Sailing":                           "features",
	"Score Attack":                      "features",
	"Story Rich":                        "features",
	"Team-Based":                        "features",
	"Text-Based":                        "features",
	"Time Manipulation":                 "features",
	"Turn-Based Combat":                 "features",
	"Tutorial":                          "features",
	"Vehicular Combat":                  "features",
	"Female Protagonist":                "features",
	"Silent Protagonist":                "features",
	"Villain Protagonist":               "features",
	"Minigames":                         "features",
	"Intentionally Awkward Controls":    "features",

	"4 Player Local":           "players",
	"Asynchronous Multiplayer": "players",
	"Co-op":                    "players",
	"Co-op Campaign":           "players",
	"Local Co-op":              "players",
	"Local Multiplayer":        "players",
	"Massively Multiplayer":    "players",
	"Multiplayer":              "players",
	"Online Co-Op":             "players",
	"Singleplayer":             "players",

	"Based On A Novel":     "other",
	"Batman":               "other",
	"Documentary":          "other",
	"Drama":                "other",
	"Dungeons & Dragons":   "other",
	"Episodic":             "other",
	"Experience":           "other",
	"Feature Film":         "other",
	"Games Workshop":       "other",
	"Indie":                "other",
	"LEGO":                 "other",
	"Mod":                  "other",
	"Movie":                "other",
	"Music":                "other",
	"Real-Time":            "other",
	"Real-Time with Pause": "other",
	"Remake":               "other",
	"Sequel":               "other",
	"Soundtrack":           "other",
	"Time Attack":          "other",
	"Turn-Based":           "other",
	"Warhammer 40K":        "other",

	"Animation & Modeling":  "software",
	"Audio Production":      "software",
	"Benchmark":             "software",
	"Design & Illustration": "software",
	"GameMaker":             "software",
	"Gaming":                "software",
	"Photo Editing":         "software",
	"RPGMaker":              "software",
	"Software":              "software",
	"Software Training":     "software",
	"Utilities":             "software",
	"Video Production":      "software",
	"Web Publishing":        "software",

	"Addictive":        "assessments",
	"Beautiful":        "assessments",
	"Classic":          "assessments",
	"Competitive":      "assessments",
	"Cult Classic":     "assessments",
	"Difficult":        "assessments",
	"Emotional":        "assessments",
	"Epic":             "assessments",
	"Fast-Paced":       "assessments",
	"Funny":            "assessments",
	"Great Soundtrack": "assessments",
	"Lore-Rich":        "assessments",
	"Masterpiece":      "assessments",
	"Psychological":    "assessments",
	"Relaxing":         "assessments",
	"Replay Value":     "assessments",
	"Short":            "assessments",
	"Unforgiving":      "assessments",
	"Comedy":           "assessments",
	"Dark Comedy":      "assessments",

	"Blood":          "ratings",
	"Gore":           "ratings",
	"Mature":         "ratings",
	"NSFW":           "ratings",
	"Nudity":         "ratings",
	"Sexual Content": "ratings",
	"Violent":        "ratings",

	"Controller":     "hardware-input",
	"Hardware":       "hardware-input",
	"Mouse only":     "hardware-input",
	"Steam Machine":  "hardware-input",
	"Touch-Friendly": "hardware-input",
	"TrackIR":        "hardware-input",
	"Voice Control":  "hardware-input",

	"Crowdfunded":  "funding",
	"Early Access": "funding",
	"Free to Play": "funding",
	"Kickstarter":  "funding",

	// ADDED TAGS NOT INCLUDED IN THE DOCUMENTATION
	"Zombies":             "themes & moods",
	"Dark Humor":          "themes & moods",
	"Puzzle-Platformer":   "sub-genre",
	"Dwarf":               "themes & moods",
	"Action RTS":          "sub-genre",
	"Party Game":          "sub-genre",
	"Well-Written":        "assessments",
	"Spaceships":          "themes & moods",
	"Reboot":              "themes & moods",
	"Immersive":           "assessments",
	"Party":               "sub-genre",
	"Hentai":              "ratings",
	"Boomer Shooter":      "sub-genre",
	"Football (American)": "genre",
	"Cooking":             "sub-genre",
	"Musou":               "sub-genre",
	"Jump Scare":          "features",
	"Vikings":             "themes & moods",
	"Narrative":           "assessments",
	"Ambient":             "themes & moods",
	"Cricket":             "genre",
	"Electronic Music":    "features",
	"Mahjong":             "genre",
	"Farming":             "sub-genre",
	"Escape Room":         "features",
	// WERE NOT PRESENT WHEN THE DATABASE WAS FILLED
	"Creature Collector":    "sub-genre",
	"Roguelike Deckbuilder": "sub-genre",
	"Extraction Shooter":    "sub-genre",
	"Boss Rush":             "features",
	"Shop Keeper":           "sub-genre",
	"Job Simulator":         "sub-genre",
	"Fishing":               "sub-genre",
	"Wholesome":             "assessments",
	"Cozy":                  "assessments",
	"Elf":                   "themes & moods",
	"Rock Music":            "features",
	"Dice":                  "sub-genre",
	"Electronic":            "themes & moods",
	"Coding":                "features",
	"Snooker":               "genre",
	"Fox":                   "themes & moods",
	"Hobby Sim":             "sub-genre",
	"Instrumental Music":    "features",
	"Birds":                 "themes & moods",
	"Volleyball":            "genre",
	"8-bit Music":           "features",
	"Rugby":                 "genre",
	"Social Deduction":      "sub-genre",
}

var initialTagWeights = map[string]float64{
	"Action":     0.0,
	"Adventure":  0.0,
	"Casual":     0.0,
	"Puzzle":     0.0,
	"Racing":     0.0,
	"RPG":        0.0,
	"Simulation": 0.0,
	"Sports":     0.0,
	"Strategy":   0.0,
	"Tabletop":   0.0,

	"Action RPG":            0.0,
	"Action-Adventure":      0.0,
	"Arcade":                0.0,
	"Auto Battler":          0.0,
	"Automobile Sim":        0.0,
	"Base-Building":         0.0,
	"Baseball":              0.0,
	"Basketball":            0.0,
	"Battle Royale":         0.0,
	"BMX":                   0.0,
	"Board Game":            0.0,
	"Bowling":               0.0,
	"Building":              0.0,
	"Card Game":             0.0,
	"Character Action Game": 0.0,
	"Chess":                 0.0,
	"Clicker":               0.0,
	"Cycling":               0.0,
	"Diplomacy":             0.0,
	"e-sports":              0.0,
	"Experimental":          0.0,
	"Exploration":           0.0,
	"Farming Sim":           0.0,
	"Fighting":              0.0,
	"Football":              0.0,
	"God Game":              0.0,
	"Golf":                  0.0,
	"Hacking":               0.0,
	"Hidden Object":         0.0,
	"Hockey":                0.0,
	"Idler":                 0.0,
	"Interactive Fiction":   0.0,
	"Management":            0.0,
	"Match 3":               0.0,
	"Medical Sim":           0.0,
	"Mini Golf":             0.0,
	"Mining":                0.0,
	"MMORPG":                0.0,
	"MOBA":                  0.0,
	"Motocross":             0.0,
	"Open World":            0.0,
	"Outbreak Sim":          0.0,
	"Party-Based RPG":       0.0,
	"Pinball":               0.0,
	"Platformer":            0.0,
	"Point & Click":         0.0,
	"Rhythm":                0.0,
	"Rogue-like":            0.0,
	"RTS":                   0.0,
	"Sandbox":               0.0,
	"Shooter":               0.0,
	"Skateboarding":         0.0,
	"Skating":               0.0,
	"Skiing":                0.0,
	"Snowboarding":          0.0,
	"Football (Soccer)":     0.0,
	"Space Sim":             0.0,
	"Stealth":               0.0,
	"Strategy RPG":          0.0,
	"Survival":              0.0,
	"Tennis":                0.0,
	"Tower Defense":         0.0,
	"Trivia":                0.0,
	"Turn-Based Strategy":   0.0,
	"Visual Novel":          0.0,
	"Walking Simulator":     0.0,
	"Word Game":             0.0,
	"Wrestling":             0.0,

	"2D Fighter":                0.0,
	"2D Platformer":             0.0,
	"3D Fighter":                0.0,
	"3D Platformer":             0.0,
	"4X":                        0.0,
	"Action Roguelike":          0.0,
	"Arena Shooter":             0.0,
	"Beat 'em up":               0.0,
	"Bullet Hell":               0.0,
	"Card Battler":              0.0,
	"Choose Your Own Adventure": 0.0,
	"City Builder":              0.0,
	"Collectathon":              0.0,
	"Colony Sim":                0.0,
	"Combat Racing":             0.0,
	"CRPG":                      0.0,
	"Dating Sim":                0.0,
	"Dungeon Crawler":           0.0,
	"Education":                 0.0,
	"Flight":                    0.0,
	"FPS":                       0.0,
	"Grand Strategy":            0.0,
	"Hack and Slash":            0.0,
	"Heist":                     0.0,
	"Hero Shooter":              0.0,
	"Horror":                    0.0,
	"Immersive Sim":             0.0,
	"Investigation":             0.0,
	"JRPG":                      0.0,
	"Life Sim":                  0.0,
	"Looter Shooter":            0.0,
	"Metroidvania":              0.0,
	"Mystery Dungeon":           0.0,
	"On-Rails Shooter":          0.0,
	"Open World Survival Craft": 0.0,
	"Political Sim":             0.0,
	"Precision Platformer":      0.0,
	"Programming":               0.0,
	"Real Time Tactics":         0.0,
	"Rogue-lite":                0.0,
	"Roguevania":                0.0,
	"Runner":                    0.0,
	"Shoot 'Em Up":              0.0,
	"Side Scroller":             0.0,
	"Sokoban":                   0.0,
	"Solitaire":                 0.0,
	"Souls-like":                0.0,
	"Spectacle fighter":         0.0,
	"Spelling":                  0.0,
	"Psychological Horror":      0.0,
	"Survival Horror":           0.0,
	"Tactical RPG":              0.0,
	"Third-Person Shooter":      0.0,
	"Time Management":           0.0,
	"Top-Down Shooter":          0.0,
	"Trading":                   0.0,
	"Trading Card Game":         0.0,
	"Traditional Roguelike":     0.0,
	"Turn-Based Tactics":        0.0,
	"Twin Stick Shooter":        0.0,
	"Typing":                    0.0,
	"Wargame":                   0.0,

	"2.5D":           0.0,
	"2D":             0.0,
	"360 Video":      0.0,
	"3D":             0.0,
	"3D Vision":      0.0,
	"Abstract":       0.0,
	"Anime":          0.0,
	"Cartoon":        0.0,
	"Cartoony":       0.0,
	"Cinematic":      0.0,
	"Colorful":       0.0,
	"Comic Book":     0.0,
	"Cute":           0.0,
	"First-Person":   0.0,
	"Hand-drawn":     0.0,
	"Isometric":      0.0,
	"Minimalist":     0.0,
	"Noir":           0.0,
	"Pixel Graphics": 0.0,
	"Psychedelic":    0.0,
	"Realistic":      0.0,
	"Split Screen":   0.0,
	"Stylized":       0.0,
	"Third Person":   0.0,
	"Top-Down":       0.0,
	"Voxel":          0.0,
	"VR":             0.0,

	"1980s":             0.0,
	"1990's":            0.0,
	"Agriculture":       0.0,
	"Aliens":            0.0,
	"Alternate History": 0.0,
	"America":           0.0,
	"Atmospheric":       0.0,
	"Assassin":          0.0,
	"Bikes":             0.0,
	"Capitalism":        0.0,
	"Cats":              0.0,
	"Cold War":          0.0,
	"Conspiracy":        0.0,
	"Crime":             0.0,
	"Cyberpunk":         0.0,
	"Dark":              0.0,
	"Dark Fantasy":      0.0,
	"Demons":            0.0,
	"Destruction":       0.0,
	"Detective":         0.0,
	"Dinosaurs":         0.0,
	"Dog":               0.0,
	"Dragons":           0.0,
	"Dynamic Narration": 0.0,
	"Economy":           0.0,
	"Faith":             0.0,
	"Family Friendly":   0.0,
	"Fantasy":           0.0,
	"Foreign":           0.0,
	"Futuristic":        0.0,
	"Gambling":          0.0,
	"Game Development":  0.0,
	"Gothic":            0.0,
	"Historical":        0.0,
	"Horses":            0.0,
	"Illuminati":        0.0,
	"Jet":               0.0,
	"Lemmings":          0.0,
	"LGBTQ+":            0.0,
	"Logic":             0.0,
	"Loot":              0.0,
	"Lovecraftian":      0.0,
	"Magic":             0.0,
	"Mars":              0.0,
	"Mechs":             0.0,
	"Medieval":          0.0,
	"Memes":             0.0,
	"Military":          0.0,
	"Modern":            0.0,
	"Motorbike":         0.0,
	"Mystery":           0.0,
	"Mythology":         0.0,
	"Nature":            0.0,
	"Naval":             0.0,
	"Ninja":             0.0,
	"Offroad":           0.0,
	"Old School":        0.0,
	"Otome":             0.0,
	"Parkour":           0.0,
	"Philosophical":     0.0,
	"Pirates":           0.0,
	"Political":         0.0,
	"Politics":          0.0,
	"Pool":              0.0,
	"Post-apocalyptic":  0.0,
	"Nostalgia":         0.0,
	"Retro":             0.0,
	"Robots":            0.0,
	"Romance":           0.0,
	"Rome":              0.0,
	"Satire":            0.0,
	"Science":           0.0,
	"Sci-fi":            0.0,
	"Sniper":            0.0,
	"Snow":              0.0,
	"Space":             0.0,
	"Steampunk":         0.0,
	"Submarine":         0.0,
	"Superhero":         0.0,
	"Supernatural":      0.0,
	"Surreal":           0.0,
	"Swordplay":         0.0,
	"Tactical":          0.0,
	"Tanks":             0.0,
	"Thriller":          0.0,
	"Time Travel":       0.0,
	"Trains":            0.0,
	"Transhumanism":     0.0,
	"Transportation":    0.0,
	"Underground":       0.0,
	"Underwater":        0.0,
	"Vampire":           0.0,
	"War":               0.0,
	"Werewolves":        0.0,
	"Western":           0.0,
	"World War I":       0.0,
	"World War II":      0.0,

	"6DOF":                              0.0,
	"Archery":                           0.0,
	"Artificial Intelligence":           0.0,
	"Asymmetric VR":                     0.0,
	"ATV":                               0.0,
	"Automation":                        0.0,
	"Boxing":                            0.0,
	"Bullet Time":                       0.0,
	"Character Customization":           0.0,
	"Choices Matter":                    0.0,
	"Class-Based":                       0.0,
	"Combat":                            0.0,
	"Conversation":                      0.0,
	"Crafting":                          0.0,
	"Deckbuilding":                      0.0,
	"Driving":                           0.0,
	"FMV":                               0.0,
	"Grid-Based Movement":               0.0,
	"Gun Customization":                 0.0,
	"Hex Grid":                          0.0,
	"Hunting":                           0.0,
	"Inventory Management":              0.0,
	"Level Editor":                      0.0,
	"Linear":                            0.0,
	"Martial Arts":                      0.0,
	"Moddable":                          0.0,
	"Multiple Endings":                  0.0,
	"Music-Based Procedural Generation": 0.0,
	"Narration":                         0.0,
	"Naval Combat":                      0.0,
	"Nonlinear":                         0.0,
	"Perma Death":                       0.0,
	"Physics":                           0.0,
	"Procedural Generation":             0.0,
	"PvE":                               0.0,
	"PvP":                               0.0,
	"Quick-Time Events":                 0.0,
	"Resource Management":               0.0,
	"Sailing":                           0.0,
	"Score Attack":                      0.0,
	"Story Rich":                        0.0,
	"Team-Based":                        0.0,
	"Text-Based":                        0.0,
	"Time Manipulation":                 0.0,
	"Turn-Based Combat":                 0.0,
	"Tutorial":                          0.0,
	"Vehicular Combat":                  0.0,
	"Female Protagonist":                0.0,
	"Silent Protagonist":                0.0,
	"Villain Protagonist":               0.0,
	"Minigames":                         0.0,
	"Intentionally Awkward Controls":    0.0,

	"4 Player Local":           0.0,
	"Asynchronous Multiplayer": 0.0,
	"Co-op":                    0.0,
	"Co-op Campaign":           0.0,
	"Local Co-op":              0.0,
	"Local Multiplayer":        0.0,
	"Massively Multiplayer":    0.0,
	"Multiplayer":              0.0,
	"Online Co-Op":             0.0,
	"Singleplayer":             0.0,

	"Based On A Novel":     0.0,
	"Batman":               0.0,
	"Documentary":          0.0,
	"Drama":                0.0,
	"Dungeons & Dragons":   0.0,
	"Episodic":             0.0,
	"Experience":           0.0,
	"Feature Film":         0.0,
	"Games Workshop":       0.0,
	"Indie":                0.0,
	"LEGO":                 0.0,
	"Mod":                  0.0,
	"Movie":                0.0,
	"Music":                0.0,
	"Real-Time":            0.0,
	"Real-Time with Pause": 0.0,
	"Remake":               0.0,
	"Sequel":               0.0,
	"Soundtrack":           0.0,
	"Time Attack":          0.0,
	"Turn-Based":           0.0,
	"Warhammer 40K":        0.0,

	"Animation & Modeling":  0.0,
	"Audio Production":      0.0,
	"Benchmark":             0.0,
	"Design & Illustration": 0.0,
	"GameMaker":             0.0,
	"Gaming":                0.0,
	"Photo Editing":         0.0,
	"RPGMaker":              0.0,
	"Software":              0.0,
	"Software Training":     0.0,
	"Utilities":             0.0,
	"Video Production":      0.0,
	"Web Publishing":        0.0,

	"Addictive":        0.0,
	"Beautiful":        0.0,
	"Classic":          0.0,
	"Competitive":      0.0,
	"Cult Classic":     0.0,
	"Difficult":        0.0,
	"Emotional":        0.0,
	"Epic":             0.0,
	"Fast-Paced":       0.0,
	"Funny":            0.0,
	"Great Soundtrack": 0.0,
	"Lore-Rich":        0.0,
	"Masterpiece":      0.0,
	"Psychological":    0.0,
	"Relaxing":         0.0,
	"Replay Value":     0.0,
	"Short":            0.0,
	"Unforgiving":      0.0,
	"Comedy":           0.0,
	"Dark Comedy":      0.0,

	"Blood":          0.0,
	"Gore":           0.0,
	"Mature":         0.0,
	"NSFW":           0.0,
	"Nudity":         0.0,
	"Sexual Content": 0.0,
	"Violent":        0.0,

	"Controller":     0.0,
	"Hardware":       0.0,
	"Mouse only":     0.0,
	"Steam Machine":  0.0,
	"Touch-Friendly": 0.0,
	"TrackIR":        0.0,
	"Voice Control":  0.0,

	"Crowdfunded":  0.0,
	"Early Access": 0.0,
	"Free to Play": 0.0,
	"Kickstarter":  0.0,

	// ADDED TAGS NOT INCLUDED IN THE DOCUMENTATION
	"Zombies":             0.0,
	"Dark Humor":          0.0,
	"Puzzle-Platformer":   0.0,
	"Dwarf":               0.0,
	"Action RTS":          0.0,
	"Party Game":          0.0,
	"Social Deduction":    0.0,
	"Well-Written":        0.0,
	"Spaceships":          0.0,
	"Reboot":              0.0,
	"Immersive":           0.0,
	"Party":               0.0,
	"Hentai":              0.0,
	"Boomer Shooter":      0.0,
	"Football (American)": 0.0,
	"Cooking":             0.0,
	"Musou":               0.0,
	"Jump Scare":          0.0,
	"Vikings":             0.0,
	"Narrative":           0.0,
	"Ambient":             0.0,
	"Cricket":             0.0,
	"Electronic Music":    0.0,
	"Mahjong":             0.0,
	"Farming":             0.0,
	"Escape Room":         0.0,
	// WERE NOT PRESENT WHEN THE DATABASE WAS FILLED
	"Creature Collector":    0.0,
	"Roguelike Deckbuilder": 0.0,
	"Extraction Shooter":    0.0,
	"Boss Rush":             0.0,
	"Shop Keeper":           0.0,
	"Job Simulator":         0.0,
	"Fishing":               0.0,
	"Wholesome":             0.0,
	"Cozy":                  0.0,
	"Elf":                   0.0,
	"Rock Music":            0.0,
	"Dice":                  0.0,
	"Electronic":            0.0,
	"Coding":                0.0,
	"Snooker":               0.0,
	"Fox":                   0.0,
	"Hobby Sim":             0.0,
	"Instrumental Music":    0.0,
	"Birds":                 0.0,
	"Volleyball":            0.0,
	"8-bit Music":           0.0,
	"Rugby":                 0.0,
}

func GetBaseTagWeights(gameID uint32) map[string]float64 {

	tagWeights := GetInitialTagWeights()

	// get tag weights using gameID in the db
	// add only if weight > 0.0
	db := database.GetDB()
	var gameTags []models.GameTag
	var game models.Game
	db.Where("app_id = ?", gameID).Find(&game)
	real_gameID := game.ID

	result := db.Where("game_id = ?", real_gameID).Find(&gameTags)
	if result.Error != nil {
		fmt.Printf("error!!! %e\n", result.Error)
		return tagWeights
	}

	for _, tag := range gameTags {
		if tag.Weight > 0.0 {
			tagWeights[tag.TagName] = tag.Weight
		}
	}

	return tagWeights

}

func NormalizeTagWeights(gameTags []models.GameTag) []models.GameTag {
	if len(gameTags) == 0 {
		return gameTags
	}

	tagCategories := GetAllTagCategories()

	tagsWithCategories := GetAllPossibleTags()

	// add up category totals with tag counts
	categoryTotals := make(map[string]float64)
	for _, category := range tagCategories {
		categoryTotals[category] = 0.0
	}
	for _, tag := range gameTags {
		tagName := strings.ToLower(tag.TagName)
		tagCount := tag.Weight
		category := tagsWithCategories[tagName]
		categoryTotals[category] += tagCount
	}

	// calculate normalized weights as tag count relative to category total
	normalizedTags := gameTags
	for i := range normalizedTags {
		tagName := strings.ToLower(normalizedTags[i].TagName)
		tagCount := normalizedTags[i].Weight
		category := tagsWithCategories[tagName]
		if categoryTotals[category] > 0 {
			normalizedTags[i].Weight = tagCount / categoryTotals[category]
		}
	}

	return normalizedTags
}

func GetAllTagCategories() []string {
	return allTagCategories
}

func GetTagCategoryWeights() map[string]float64 {
	return tagCategoryWeights
}
func GetAllPossibleTags() map[string]string {
	return allPossibleTags
}

func GetInitialTagWeights() map[string]float64 {
	return initialTagWeights
}